In [69]:
!activate tensor
!pip install sklearn
!pip install pandas
!pip install numpy

In [70]:
import pandas as pd
import sklearn
import numpy as np
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn import model_selection

In [71]:
# download data
data = pd.read_csv("student-mat.csv",sep = ";")
print (data.head)

<bound method NDFrame.head of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freet

In [72]:
data = data[["G1","G2","G3","studytime","failures","absences"]]
print(data.head)

<bound method NDFrame.head of      G1  G2  G3  studytime  failures  absences
0     5   6   6          2         0         6
1     5   5   6          2         0         4
2     7   8  10          2         3        10
3    15  14  15          3         0         2
4     6  10  10          2         0         4
..   ..  ..  ..        ...       ...       ...
390   9   9   9          2         2        11
391  14  16  16          1         0         3
392  10   8   7          1         3         3
393  11  12  10          1         0         0
394   8   9   9          1         0         5

[395 rows x 6 columns]>


In [73]:
predict = "G3"
X = np.array(data.drop([predict],1))
y = np.array(data[predict])
print(X)
X_label = ["G1", "G2", "studytime", "failures", "absences"]
print(X_label)

[[ 5  6  2  0  6]
 [ 5  5  2  0  4]
 [ 7  8  2  3 10]
 ...
 [10  8  1  3  3]
 [11 12  1  0  0]
 [ 8  9  1  0  5]]
['G1', 'G2', 'studytime', 'failures', 'absences']


In [74]:
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)
# Auto randomized


In [75]:
linear = linear_model.LinearRegression()

linear.fit(X_train,y_train)
acc = linear.score(X_test,y_test)
print(acc)

0.8903827493236648


In [76]:
print("Coefficients: \n", linear.coef_)
print("\nIntercept: \n", linear.intercept_)



Coefficients: 
 [ 0.1569118   0.98338254 -0.20381345 -0.23667015  0.03775665]

Intercept: 
 -1.58375728629143


In [77]:
predictions = linear.predict(X_test)
print(predictions)
# Creating an array of all predicted values based on X_test values

[15.49059747 10.742277    8.36427437 12.19801459 10.8656772  11.76930139
  7.24914046  8.49780481  8.75884158 -0.46916778  8.50034024 11.12408856
  9.33016075 11.91280264 11.98831595  8.57920331  6.16344403  9.48707255
 14.95611916 11.29268078  5.10454819  9.51624915  6.37412793 -0.57917794
  3.36080233  7.65531864 13.49522074 13.87304813  7.43302377  9.56258585
  9.80089616  4.01802594 10.02743607 12.14522775 12.57584199 17.0328944
 12.62862883 11.00493341 10.23802998  8.1898664 ]


In [78]:
print(X_test)

[[15 15  2  0 10]
 [13 11  2  1  3]
 [ 9  9  2  2 15]
 [12 12  1  0  8]
 [13 11  2  0  0]
 [14 12  2  1  0]
 [ 8  8  1  1  4]
 [ 9  9  2  0  6]
 [11  9  3  0 10]
 [11  0  3  0  0]
 [ 7 10  3  1  0]
 [12 11  2  0 11]
 [ 9 10  2  0  2]
 [11 12  2  0 10]
 [11 12  2  0 12]
 [10  9  2  0  4]
 [ 6  7  2  1 15]
 [10 10  2  0  2]
 [14 15  2  0  0]
 [10 12  2  1  4]
 [ 6  6  2  1 13]
 [ 8  9  1  1 38]
 [ 8  7  2  0  6]
 [ 9  0  2  0  0]
 [ 6  5  1  3  0]
 [ 9  8  2  1 16]
 [14 13  1  0  8]
 [15 14  4  0  4]
 [ 8  8  2  0  8]
 [10 10  2  0  4]
 [12 10  2  0  2]
 [ 6  5  2  0  4]
 [12 10  2  0  8]
 [12 12  2  0 12]
 [13 13  4  0  4]
 [16 17  3  0  0]
 [13 13  3  0  0]
 [11 11  2  0 12]
 [ 9 11  2  0  0]
 [ 8  9  2  0  2]]


In [79]:
for x in range(len(predictions)):
    print(predictions[x], X_test[x], y_test[x])
# Observe how close the predictions are to y_test

print(y_test - predictions)
# Differences in hypothesis vs test values

15.490597474971896 [15 15  2  0 10] 15
10.74227700051454 [13 11  2  1  3] 11
8.364274371499652 [ 9  9  2  2 15] 9
12.198014591186007 [12 12  1  0  8] 12
10.865677198070152 [13 11  2  0  0] 10
11.769301389246916 [14 12  2  1  0] 12
7.2491404627341325 [8 8 1 1 4] 8
8.497804812510864 [9 9 2 0 6] 10
8.75884157862745 [11  9  3  0 10] 10
-0.46916778410540116 [11  0  3  0  0] 0
8.500340235901184 [ 7 10  3  1  0] 10
11.124088559056268 [12 11  2  0 11] 11
9.330160745829307 [ 9 10  2  0  2] 9
11.912802642427458 [11 12  2  0 10] 13
11.9883159451608 [11 12  2  0 12] 11
8.579203313824786 [10  9  2  0  4] 9
6.163444033443232 [ 6  7  2  1 15] 8
9.487072549876572 [10 10  2  0  2] 10
14.956119157257923 [14 15  2  0  0] 15
11.292680778524542 [10 12  2  1  4] 12
5.104548191924762 [ 6  6  2  1 13] 8
9.516249147986075 [ 8  9  1  1 38] 8
6.374127930893346 [8 7 2 0 6] 9
-0.5791779447553032 [9 0 2 0 0] 0
3.3608023295062903 [6 5 1 3 0] 0
7.655318635736823 [ 9  8  2  1 16] 7
13.495220738065665 [14 13  1  0  8] 

In [94]:
G1 = int(input("Insert G1 here: "))
G2 = int(input("Insert G2 here: "))
st = int(input("Insert studytime here: "))
fail = int(input("Insert number of failures here: "))
absence = int(input("Insert number of absences here: "))                  

predict_feature = ([[G1,G2,st,fail,absence]])
predict_grade = float((linear.predict(predict_feature)))
predict_grade = round(predict_grade)
print("Predicted grade is: " + str((predict_grade)))

Insert G1 here: 11
Insert G2 here: 11
Insert studytime here: 2
Insert number of failures here: 0
Insert number of absences here: 4
Predicted grade is: 11


In [93]:
predict_grade
predict_grade 

10.702880195442306